# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

# docker build -f Dockerfile.dev -t <nom_user>/<image> .
# docker run -p 5173:5173 --name <name_container> <nom_user>/<image>
# -f Dockerfile.dev : indique à Docker d’utiliser le Dockerfile de développement.
# -t kenlark/app-portofolio-dev : tague l’image avec un nom personnalisé.
