name: Notifications Bot Discord

on:
  push:
    branches:
      - main # Exécuter pour les push vers la branche principale
    tags:
      - "v*.*.*" # Exécuter pour les tags de version (ex: v1.0.0)
  pull_request:
    types: [opened, reopened] # Exécuter pour les PR ouvertes, réouvertes
    branches:
      - main # Exécuter pour les pull requests vers la branche principale
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Envoi de notification Discord
        uses: stegzilla/discord-notify@v2
        with:
          webhook-url: ${{ secrets.Notifications_Bot_Discord }}
          title: "Nouvelle PR"
          message: |
            **Nouvelle PR ouverte :** ${{ github.event.pull_request.title }}
            **Auteur :** ${{ github.event.pull_request.user.login }}
            **Description :** ${{ github.event.pull_request.body }}
          includes-image: true
          image-url: ${{ github.event.pull_request.user.avatar_url }}
          username: "Notifications d'une nouvelle PR"
