name: Notifications Bot Discord

on:
  pull_request:
    types: [opened, reopened] # Exécuter pour les PR ouvertes, réouvertes

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Envoi de notification Discord
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.Notifications_Bot_Discord }}
          title: "Nouvelle PR"
          message: |
            **Nouvelle PR ouverte :** ${{ github.event.pull_request.title }}
            **Auteur :** ${{ github.event.pull_request.user.login }}
            **Description :** ${{ github.event.pull_request.body || "Pas de description fournie" }}
          includes_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: "Notifications d'une nouvelle PR"
