name: continuous-integration

on:
  push:
    branches:
      - main # Exécuter pour les push vers la branche principale
    tags:
      - "v*.*.*" # Exécuter pour les tags de version (ex: v1.0.0)
  pull_request:
    branches:
      - main # Exécuter pour les pull requests vers la branche principale
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Execute toutes les heures

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build step
        run: npm ci && npm run build

  test:
    needs: build # Ne se lance que si le build réussit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: echo "Executing tests here..."

  deploy:
    needs: test # Ne se lance que si les tests réussissent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy step
        run: echo "Deploying application here..."
