name: continuous-integration

on:
  push:
    branches:
      - main # Exécuter pour les push vers la branche principale
    tags:
      - "v*.*.*" # Exécuter pour les tags de version (ex: v1.0.0)
  pull_request:
    branches:
      - main # Exécuter pour les pull requests vers la branche principale
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build step
        run: npm ci && npm run build

  test:
    needs: build # Ne se lance que si le build réussit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: echo "Executing tests here..."

  deploy:
    needs: test # Ne se lance que si les tests réussissent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app-portofolio:latest .

      - name: Push de l'image Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app-portofolio:latest
