name: issue-response

on:
  issues:
    types: [opened, edited]

  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  respond_to_issue:
    if: github.event.issue.state == 'open' && github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Envoie une réponse automatique à l'issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = 'Merci pour votre issue ! Nous allons l\'examiner dès que possible. Si le problème est résolu, écrivez "close" dans un commentaire pour fermer l\'issue.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });

      - name: Fermer l'issue si le commentaire contient "close"
        if: contains(github.event.comment.body, 'close')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
