name: issue-response

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Envoie une réponse automatique à l'issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = 'Merci pour votre issue ! Nous allons l\'examiner dès que possible. Si le problème est résolu, écrivez "close" dans un commentaire pour fermer l\'issue.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
