name: issue-response

on:
  issues:
    types: [opened, edited]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Send response
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Merci pour votre issue ! Nous allons l\'examiner dès que possible.'
            })

      - name: Close issue if title contains "close"
        if: contains(github.event.issue.title, 'close')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            })
