name: CI pour les Pull Requests

on:
  pull_request:
    branches:
      - main # Exécuter pour les pull requests vers la branche principale
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Étape de build
        run: npm ci && npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Étape de test
        run: echo "Exécution des tests ici..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extraire le tag Git
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # GITHUB_REF contient refs/tags/v1.2.3
      # La syntaxe Bash ${GITHUB_REF#refs/tags/} enlève le préfixe refs/tags/ pour ne garder que v1.2.3

      - name: Build de l'image Docker
        run: docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/app-portofolio:${{ env.TAG }} .

      - name: Push de l'image Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app-portofolio:${{ env.TAG }}
